#开发环境
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?useUnicode=yes&characterEncoding=UTF8&useSSL=false
    password: weile1314
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  freemarker:
    settings:
      number_format: 0.##
  redis:
     host: localhost
     port: 6379
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
weburl:
  img-prefix: https://p0.cdrysj.com/po
upload:
  path: /Users/zhaoxiang/update
  waterMarkPath: /Users/zhaoxiang/update




