#开发环境
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?useUnicode=yes&characterEncoding=UTF8&useSSL=false
    password: yhyc2018
    username: news
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  freemarker:
    settings:
      number_format: 0.##
  redis:
     host: localhost
     port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml
weburl:
  img-prefix: https://p0.cdrysj.com/po
server:
  port: 9099
